title: SuperMap iDesktop Cross 8C
subtitle: "跨平台、全开源、可定制"
description: "SuperMap iDesktop Cross 8C是一款支持跨平台的桌面GIS应用与开发平台，是超图新一代的开源GIS桌面产品。"
author: iDesktop
language: en
timezone: UTC
url: http://qinlj.github.io/iDesktop-Cross
root: /
permalink: news/:year/:month/:day/:title/
archive_dir: news
code_dir: downloads/code
new_post_name: :year-:month-:day-:title.md # File name of new posts
post_asset_folder: true
highlight:
  enable: true
  line_number: false
per_page: 0

theme: navy
deploy:
  type: git
  repo: git@github.com:qinlj/iDesktop-Cross-Docs.git
  branch: gh-pages

disqus_shortname: hexojs
google_analytics: UA-4910098-10
fb_admins: 100000247608790
algolia:
  en:
    api_key: c3d5d4c995b5e0c2ffb5623900279a66
    index_name: hexo
  zh-tw:
    api_key: c83d2ec3440f40aec6d0e695ecec7ef3
    index_name: hexo_zh-tw
  zh-cn:
    api_key: cdea7d4e47d84f6145b77e7f68689f35
    index_name: hexo_zh-cn
twitter: qinlj
github: qinlj/iDesktop-Cross-Docs

